### PR TITLE
[ Feature 🚀 ] Implemented Asymetric encryption algorithm RSA256 when signing and verifying JWT tokens

### PR DESCRIPTION
**Pull request by ZeroThread**
When creating `jsonwebtoken` rather than signing and verifying tokens with a secret key use Asymetric encryption `(RSA 256)` instead, using pubic and private key pairs. 

Use the 
- `private key` to sign the JWT token 
- `public key` to verify the token

```bash
- First create the private key after which you can create a public key.
 
/** To generate a public and private key key pair */

// Private Key
>> openssl genrsa -out private_key.pem 4096

// Public Key
>> openssl rsa -pubout -in private_key.pem -out public_key.pem
```

### CODE REVIEW

**Review by learning-zone — CHANGES_REQUESTED** [review]
Thanks for the PR ! :)
Please create a PR to add this as new Question instead of updating the existing one.

**Comment by ZeroThread** [comment]
Okay I will do that now. Thanks.

**Comment by ZeroThread** [comment]
So I refactored the code to restore previous files I edited in my previous commit to how they where initially and then created a new folder to reflect the new changes where I discussed in detail's how to implement signing and verifying JWT tokens using asymmetric cyrptography.

I added a new question instead of editing the previous one :-
This is the link to the question on the readme file.
[ How to implement asymmetric cryptography when signing and verify JSON Web Token (JWT) for authentication in node js?](https://github.com/ZeroThread/nodejs-interview-questions#q-how-to-implement-asymmetric-cryptography-when-signing-and-verifying-json-web-token-jwt-for-authentication-in-node-js)

**Comment by learning-zone** [comment]
There are lot of changes in this PR, Hence closing this.
You could create a new one.

**Pull request closed without merging**
